Paginate = 10
baseURL = "https://mauriciotosi.github.io/PIClab/"
defaultContentLanguage = "es"
disqusShortname = ""
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
preserveTaxonomyNames = true
publishDir = "docs"
pygmentsCodefences = true
theme = "engimo"
title = "Laboratorio"
[blackfriday]
hrefTargetBlank = true
[languages.en]
lang = "en"
languageName = "English"
weight = 1
[languages.es]
lang = "es"
languageName = "Spanish"
weight = 1
[[menu.main]]
name = "Diseños"
url = "/diseños/"
weight = 6
[[menu.main]]
identifier = "procesos"
name = "Procesos"
url = "/procesos/"
weight = 4
[[menu.main]]
identifier = "obleas"
name = "Obleas"
url = "/obleas/"
weight = 2
[[menu.main]]
identifier = "recetas"
name = "Recetas"
url = "/recetas/"
weight = 5
[[menu.main]]
identifier = "equipos"
name = "Equipos"
url = "/equipos/"
weight = 3
[[menu.main]]
identifier = "muestras"
name = "Muestras"
url = "/muestras/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params.assets]
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = ""
[params.comments]
enable = false
[params.comments.staticman]
apiEndpoint = "https://api.staticman.net/v2/entry"
enable = true
maxDepth = 2
[params.info]
description = "Apuntes, Recetas e Historial de muestras"
title404 = "Nothing's here!"
[params.search]
client = "lunr"
[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""
[params.seo]
titleSeparator = "•"
[params.settings]
accentColor = "#44ccff"
archiveDateFormat = "Jan 02"
dateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"]
hideMainMenu = false
listDateFormat = "2006, Jan 02"
showReadingTime = false
taxonomyCloudShuffle = false
[params.sidebar]
enable = true
[params.social]
email = "mauriciotosi@cnea.gov.ar"
github = "mauriciotosi/PIClab"
[params.widgets]
footer = ["social_menu"]
homepage = ["recent_posts"]
sidebar = ["about", "sidebar_menu"]
[permalinks]
page = "/:slug/"
[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
